### ISSUE TITLE
Verified Contracts statistics quantity error

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#190]
**System Specs:**
 - OS:
 - Blockscout Version/branch: blockscout

**Describe the bug**
    Verified Contracts/Contracts Statistics: Confirm whether to display the total number under the current environment

**To Reproduce**
1. Go to 'Verified Contracts'
2. Check the displayed quantity of Verified Contracts/Contracts
3. See error

**Expected behavior**
   Verified Contracts/The displayed quantity is consistent with the database

**Screenshots**
![image](https://user-images.githubusercontent.com/106131461/228506964-b561b017-3ef3-4d93-86e5-cb8d622cd536.png)

**Additional context**
   Verified Contracts/Contracts The data displayed at this location needs to be confirmed, indicating whether the total quantity is displayed or whether there is a difference

**Comment by Jaycelv** [comment]
The total count is obtained by querying the Addresses table with a condition of the existence of the contract_code field. The count for the last 24 hours is obtained by querying the Transactions table with the created_contract_code_indexed_at field, which is updated to the current time when the data is inserted, and filtering for values less than 24 hours ago. The count of verified contracts is obtained by querying the stmart_contracts table.
