### ISSUE TITLE
The list Address column of Verified Contracts cannot be clicked to view the details

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#191]
**System Specs:**
 - OS:
 - Blockscout Version/branch: blockscout

**Describe the bug**
    The list Address column of Verified Contracts cannot be clicked to view the details, and clicking is not possible

**To Reproduce**
1. Go to 'Verified Contracts'
2. Click on 'Address column arbitrary content'
3. See error

**Expected behavior**
    The content of the Address column in the list of Verified Contracts supports clicking

**Screenshots**
![image](https://user-images.githubusercontent.com/106131461/228508239-1c399c0e-bc2f-498b-8a41-241a118f8d95.png)

**Comment by Jaycelv** [comment]
I upgrade code to v5.0.0-beta, and the issue is not exist
