### ISSUE TITLE
The token name in the tokens all list is empty

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#194]
**System Specs:**
 - OS:
 - Blockscout Version/branch:  qa

**Describe the bug**
   The value of token name cannot be obtained in the token list

**To Reproduce**
1. Go to 'tokens - all'
2. View the tokens list
3. Click on 'address'

**Expected behavior**
   The token name of the token list does not have a value that cannot be retrieved

**Screenshots**
![22fa5835-9066-4a83-bc49-1b95386cc417](https://user-images.githubusercontent.com/106131461/229010956-3f2ecb82-bf8a-4702-823e-31e89c0a5ff6.jpeg)
![6bd61a30-a1ec-4879-9fa2-b368349b4f43](https://user-images.githubusercontent.com/106131461/229010976-9938d176-8512-4ae5-b45f-360759d31a52.jpeg)

**Comment by Jaycelv** [comment]
This token's name and symbol is empty
