### ISSUE TITLE
Abnormal page after adding transaction tags to my account

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#206]
**System Specs:**
 - OS:
 - Blockscout Version/branch: Qa

**Describe the bug**
    Move down the display area of the transaction tags page for my account

**To Reproduce**
1. Go to 'My account'
2. Click on 'transaction tags'
3. See error

**Expected behavior**
   After adding transaction tags to my account, the page will display normally

**Screenshots**
![image](https://user-images.githubusercontent.com/106131461/233915156-1219e505-45aa-431e-900d-875b42f8d637.png)

**Comment by Jaycelv** [comment]
This is correct when the screen is small
