### ISSUE TITLE
Transaction Details page da fee value error

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#212]
**System Specs:**
 - OS:
 - Blockscout Version/branch: Qa

**Describe the bug**
    Transaction Details page da fee value error

**To Reproduce**
1. Go to 'Transaction Details'
2. View the value of Dafee
3. See error

**Expected behavior**
    The Transaction Details page displays the da fee value normally
    The position of the Dafee needs to be adjusted

**Screenshots**
![1754604d-4d83-470a-8efa-6bc0d5ce2f36](https://user-images.githubusercontent.com/106131461/235095898-1737ca09-a3c1-45f5-adb0-07219ece68ad.jpeg)
![36f04912-0415-4720-9bbc-a58ca906822a](https://user-images.githubusercontent.com/106131461/235095966-5a53fa9c-ddf4-494b-a956-e5c5036e776c.jpeg)

**Comment by Jaycelv** [comment]
History data reset to  "0BIT"
