### ISSUE TITLE
Switch tab pages. Repeated selection of tabs makes the display unavailable

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#31]
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:    Google
* Blockscout Version/branch:     qa/0.2.0
* Status: mandatory

**To Reproduce**
1. Go to Address Details
2. Click on  tokens tab
3. Click on List any item in the Asset column
4. Enter the token transfer list page
5. Click any address in the token transfer list

**Screenshots** 
![image](https://user-images.githubusercontent.com/106131461/204722682-fc9f77ab-a887-40ac-b099-2e8c0ffa823b.png)
![image](https://user-images.githubusercontent.com/106131461/207764496-a326937e-bee4-4e75-9b80-034385db3808.png)
![image](https://user-images.githubusercontent.com/106131461/204722862-cff4746b-c1dc-4217-bb55-398f421a7cbb.png)

**Expected behavior**  
   The tab page is displayed normally after switching and can be accessed by clicking again

**Comment by Jaycelv** [comment]
replace address token transfer path to to token path
