### ISSUE TITLE
The data on the deposit and withdraw tab pages are displayed incorrectly

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#32]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:     Google
* Blockscout Version/branch:    qa/0.2.0
* Status: mandatory

### Steps to reproduce
        After staying in the current window to execute the transaction, the data is displayed in disorder. The withdraw data will be displayed in the deposit list, otherwise the withdraw data will also be displayed in the withdraw list. Click the transaction details to jump and display normally, and the data will be displayed normally after returning to the page
![image](https://user-images.githubusercontent.com/106131461/204723992-7a3b84d7-f1dd-42fd-8d19-0f0b24eee802.png)
![image](https://user-images.githubusercontent.com/106131461/204724035-3f4c0dcd-3f90-43a1-a7be-b51d361d0b43.png)

### Expected behaviour
        1、The browser stays at the deposit/withdraw tab page to execute the transaction
        2、View the data of the deposit/withdraw tab page
        3、After viewing, the data on the deposit/withdraw tab page is displayed normally
![image](https://user-images.githubusercontent.com/106131461/204724188-8a829318-fdf2-42d4-907b-759f6a64cf3b.png)

**Comment by Jaycelv** [comment]
Prevent websocket from pushing incorrect data
