### ISSUE TITLE
View the latest push transaction record lost in the dispose tab page

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#33]
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:     Google
* Blockscout Version/branch:      qa/0.2.0
* Status: High frequency

### Steps to reproduce
        Click to jump to the dispose list of address details to view any information. After returning the dispose list, the data is displayed incorrectly (the current screenshot shows less data)
![image](https://user-images.githubusercontent.com/106131461/204724881-7a3db37e-64d3-4229-bef9-5b0bf805105d.png)
![image](https://user-images.githubusercontent.com/106131461/204724914-cf4d664c-2694-4ce6-ba3c-8ad23d7bae84.png)

### Expected behaviour
        1、View the latest push record in the dispose list of address details
        2、Return to the dispose list page after viewing
        3、Refresh the dispose page, and the data display is normal
![image](https://user-images.githubusercontent.com/106131461/204725219-1b88cc90-e770-4e95-a41f-ddb79172e13c.png)

**Comment by Jaycelv** [comment]
The reason for this bug is the same as #32
