### ISSUE TITLE
Dispose/withdr paging request error interface

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#34]
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:   Google
* Blockscout Version/branch:  qa/0.2.0
* Status: mandatory

### Steps to reproduce
        The data on the first page of the dispose/withdraw list data of address details is correct. After switching the page number, the data displayed contains the data of the opposite party

### Expected behaviour
        1、Dispose/withdraw list data>50
        2、Dispose/withdraw List Data Switch Page Number Correctly to View the List Data on the Next Page
        3、The data on the first page of the dispose/withdraw list is correct, and the opposite data is displayed on the second page
![image](https://user-images.githubusercontent.com/106131461/204740603-b767ee13-89c3-4e0b-adef-924b6a4125b7.png)
![image](https://user-images.githubusercontent.com/106131461/204740639-13f10eaf-f6b3-496c-978e-254ccb40846c.png)

### Actual behaviour
        If the data in the dispose/withdraw list is 51, switch to the next page, and only one data of the current tab item should be displayed

**Comment by Jaycelv** [comment]
The api responses wrong param, which can link the next page to token transfer page
