### ISSUE TITLE
Internal transaction list Method hover content error

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#360]
**System Specs:**
 - OS:   mac Google
 - Blockscout Version/branch:  release/v0.8.7

**Describe the bug**
    Internal transaction list Method hover content error
    example：https://explorer.qa.gomantle.org/address/0x6d3d7b3779655405eE64662E33b79A4699845C3e/internal-transactions#address-tabs

**To Reproduce**
1. Go to 'address detail'
2. Click on 'internal-transactions'
3. View 'List Content'

**Expected behavior**
    The method hover content on the internal transaction page is correct

**Screenshots**
![image](https://github.com/mantlenetworkio/blockscout/assets/106131461/84c82d41-1c43-4aeb-9ccf-ce87cef5eacf)
# After repair
![image](https://github.com/mantlenetworkio/blockscout/assets/106131461/a7534a33-f0f0-40e6-b111-feda82d4c4e3)

**Comment by dennisloh95** [comment]
Due the the previous design, the error tag is appear beside the method tag.

**Fix:**
Move error tag to error icon tooltips
