### ISSUE TITLE
 Abnormal display of transaction quantity in browser

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#49]
**System Specs:**
 - OS:   mac
 - Blockscout Version/branch: 0.2.0

**Describe the bug**
    The number of transactions displayed in the browser is abnormal. If you stay on the home page, the gap between the number of transactions displayed and the number of blokes displayed will become larger and larger

**To Reproduce**
1. Go to Browser Home Page
2. View the transaction and bloke quantity display
3. See error  The number of transactions shows that the gap between transactions and blokes is widening

**Expected behavior**
    The number of transactions and blokes shows the difference as single digits

**Screenshots**
![1663fc5b-42fc-42b1-be9a-0e98242fc536](https://user-images.githubusercontent.com/106131461/206937566-2d45c481-f230-46e0-bc6f-417dfdb18a6e.jpeg)

**Comment by Jaycelv** [comment]
transaction has the same count as block, using data of block instead of transaction
