### ISSUE TITLE
Browser can't search in small screen mode

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#55]
**System Specs:**
 - OS:  Mac  
 - Blockscout Version/branch:  0.2.0

**Describe the bug**
   Search hash/token in browser small screen mode, click search no response

**To Reproduce**
1. Go to  https://mantle-blockscout.qa.davionlabs.com/
2. Click on  input box
3. Enter anything and click Search
4. See error  Unresponsive

**Expected behavior**
    Enter any content and search, display the corresponding search results

**Screenshots**
![image](https://user-images.githubusercontent.com/106131461/207496633-3707e21d-4594-4ac8-984a-9f08028e5a5e.png)

**Comment by Jaycelv** [comment]
The input element was not be selected while search button has been clicked
