### ISSUE TITLE
Explorer API double check

### ISSUE THREAD

**Issue by HarryWong99** [mantlenetworkio/blockscout#59]
Check whether the API displayed on explorer exactly matches with Mantle API.

https://explorer.testnet.mantle.xyz/api-docs

**Comment by guoshijiang** [comment]
### query l1l2 tx api

#### request

- address: from address
- page: page
- page_size:  every page show size
- order: 0: up, 1: down
- type: 0: withdraw, 1: deposit

#### response

- l1hash
- l2hash
- value
- status
- fee
