### ISSUE TITLE
On-chain operation data dashboard

### ISSUE THREAD

**Issue by HarryWong99** [mantlenetworkio/blockscout#74]
Need to monitor below on-chain metrics and display on the dashboard:

- [ ] Dashboard backend data and API

Testnet related:
- Total transactions (transfers & contract call, excluding system tx)
- Total transaction value( BIT）（transfers, calculated in USD )
- Daily transactions volume (transfers & contract call, excluding system tx)(T-1, update at 12:00 UTC+8)
- Total Contracts deployed 
- Daily contracts increased (T-1, update at 12:00 UTC+8)
- Total addresses (Both contract address and normal address)
- Daily addresses increased (T-1, update at 12:00 UTC+8)

Bridge related:
- Total locked tokens in bridge 
   a. token symbol
   b. locked amount for each token
   c. total value in USD
- Daily tokens deposited/withdrew via the bridge (T-1, update at 12:00 UTC+8)
   [Deposit]:  symbol / amount / total value in USD;
   [Withdraw]: symbol / amount / total value in USD
- Daily deposit/withdraw transactions (T-1, update at 12:00 UTC+8)
  [Deposit]: txn amount / address amount;
  [Withdraw]: txn amount / address amount 

- [ ] Deploy a server to store the history data

- [ ] Defaultly display 30 days' data on frontend dashboard, and support to switch between the data period between 7 days / 30 days:
![image](https://user-images.githubusercontent.com/34086765/212001273-93164785-b69d-428c-bd39-23275037cfa9.png)

**Comment by aodhgan** [comment]
- do we want the data coming from blockscout or directly from the node rpc? 
- related: does this server live with this repo code? 
- is api endpoints public or internal? 
- does it need to be included alongside the existing API at https://explorer.testnet.mantle.xyz/api ?
-  how will the front end consume this data? what format and structure (an endpoint for each of the above "Testnet Related?") topics for example?
- is the front end standalone or part of the dashboard viewed at https://explorer.testnet.mantle.xyz/ ?


we can do most of the counters like this: https://github.com/mantlenetworkio/blockscout/pull/94

not sure how well it will work for the Bridge related data above tho
