### ISSUE TITLE
The browser L1 data is processed to the transaction table, including transaction category, tx_hash, etc., distinguishing between system transactions and user transactions, more detailed l1l2 message parsing, and supporting the API interface of the bridge

### ISSUE THREAD

**Issue by HarryWong99** [mantlenetworkio/blockscout#76]
Supply an API for bridge frontend to check both the L1&L2 txn hash of each deposit and withdrawal

related issue:
https://github.com/mantlenetworkio/mantle-bridge-frontend/issues/13

- change tx hash to transaction logic
- decode message to l1l2 tables

- l1l2 api for bridge
```
curl --location --request POST 'http://127.0.0.1:3000/l1l2_transaction' \
--header 'Content-Type: application/json' \
--data-raw '{
    "address": "0x595B698621f3D344Aa9130EBA52600E4C47448dc",
    "page": 1,
    "page_size": 30,
    "type": 2,
    "order_by": "DESC" 
}'
```
- user and system transaction

**Comment by guoshijiang** [comment]
pr: https://github.com/mantlenetworkio/blockscout/pull/88
