### ISSUE TITLE
Verify Execute Unknown Network Connection Error

### ISSUE THREAD

**Issue by Alisa-song** [mantlenetworkio/blockscout#97]
**System Specs:**
 - OS:  blockscout
 - Blockscout Version/branch:

**Describe the bug**
    When the contract address is verified, the loading status does not return a result, but a new tab appears in the contract address details. When the write contract is executed, the unknown network connection reports an error

**To Reproduce**
1. Go to 'Contract Address Details'
2. Click on 'code - verify'
3. See error

**Expected behavior**
   The contract address is verified and the execution result is given
   when the write contract item is executed, the corresponding prompt will be given if the network does not match

**Screenshots**
![img_v2_7cb4b505-3aa6-4779-acdd-0f04d869a07h](https://user-images.githubusercontent.com/106131461/212232385-8d7497fb-b534-419d-8402-c54678b51a9a.jpg)
![img_v2_4a38f45f-cff6-41d0-a5b3-f46e150f749h](https://user-images.githubusercontent.com/106131461/212232397-1acdfed6-7da7-46c9-92f6-29447c8b5446.jpg)

**Comment by Jaycelv** [comment]
choose correct network pls
